ex_list = [35, 16, 5, 123, 3]
ex_list.insert(0, 15)
print(ex_list)
ex_list.remove(123)
print(ex_list)
ex_list.reverse()
print(ex_list)
ex_list.sort()
print(ex_list)
ex_list.sort(reverse=True)
print(ex_list)

a = ex_list.copy()
a.append(13)
print(a)
print(ex_list)
a.clear()
print(a)
print(ex_list.count(16))
print(ex_list.index(16))
ex_list.pop()
print(ex_list)
b = ex_list.pop()
print(ex_list)
print(b)

