string = 'Hello, Ivan Ivanov'
print(len(string))
rjust = string.rjust(22)
print(rjust)
print(len(rjust))
rjust_2 = string.rjust(22, 'a')
print(rjust_2)
ljust = string.ljust(22, 'a')
split = string.split()
print(split)
split_2 = string.split("n")
print(split_2)
join = ' '.join(string)
print(join)
join_2 = '+'.join(string.split())
print(join_2)
print(len(string))
count_a = string.count('a')
count_a_in_slice = string.count('a', 4, 10)
print(count_a)
print(count_a_in_slice)
replace_string = string.replace('l', 'd')
replace_string_count = string.replace('l', 'd', 1)
print(replace_string)
print(replace_string_count)
find_I = string.find('I')
find_I_in_slice = string.find('I', 9)
print(find_I)
print(find_I_in_slice)
rfind_I = string.find('I')
print(rfind_I)
